name: athena_bus
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_map: ^8.3.0
  flutter_native_splash: ^2.4.7
  freezed_annotation: ^3.1.0
  geolocator: ^14.0.2
  hooks_riverpod: ^3.3.1
  http: ^1.6.0
  latlong2: ^0.9.1
  path: ^1.9.1
  riverpod_annotation: ^4.0.2
  sqflite: ^2.4.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  riverpod_generator: ^4.0.3
  build_runner: ^2.15.0
  riverpod_lint: ^3.1.3
  analysis_server_plugin: ^0.3.4
  freezed: ^3.2.5

flutter:
  uses-material-design: true

  fonts:
    - family: MaterialCommunityIcons
      fonts:
        - asset: assets/fonts/materialcommunityicons.ttf

flutter_launcher_icons:
  image_path: "assets/icons/solar_bus_duotone.png"

  android: true
  adaptive_icon_background: "#fcffff"
  adaptive_icon_foreground: "assets/icons/solar_bus_duotone.png"

  ios: true
  background_color_ios: "#fcffff"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#fcffff"
  image: "assets/icons/solar_bus_duotone.png"

  android_12:
    color: "#fcffff"
    image: "assets/icons/solar_bus_duotone_large.png"
